export const USER_SUBSCRIPTION_REPOSITORY = 'USER_SUBSCRIPTION_REPOSITORY';
export const SUBSCRIPTION_PLAN_REPOSITORY = 'SUBSCRIPTION_PLAN_REPOSITORY';
export const SUBSCRIPTION_OFFER_REPOSITORY = 'SUBSCRIPTION_OFFER_REPOSITORY';
