services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      NODE_ENV: development
    env_file:
      - .env.development.local
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000/health || exit 1']
      interval: 5s
      timeout: 2s
      retries: 10

  outbox-worker:
    build:
      context: .
      dockerfile: apps/outbox-worker/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.development.local
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  payment-worker:
    build:
      context: .
      dockerfile: apps/payment-worker/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.development.local
    networks:
      - backend
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      stripe-cli:
        condition: service_started

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --forward-to api:3000/payments/webhook/stripe --api-key ${STRIPE_SECRET_KEY}
    networks:
      - backend
    depends_on:
      api:
        condition: service_healthy

  db:
    extends:
      file: compose.infra.dev.yaml
      service: db

  redis:
    extends:
      file: compose.infra.dev.yaml
      service: redis

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  redisdata:
