services:
  server:
    build:
      context: .
      target: development
    volumes:
      - ./src:/usr/src/app/src
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      NODE_ENV: development
    env_file:
      - .env.development.local
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      dev_db:
        condition: service_healthy

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --forward-to server:3000/payments/webhook/stripe --api-key ${STRIPE_SECRET_KEY}
    networks:
      - backend
    depends_on:
      - server

  dev_db:
    image: postgres:18-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streaming-service-dev
    networks:
      - backend
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
networks:
  backend:
    driver: bridge
