export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const USERS_REPOSITORY = 'USER_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const GENRES_REPOSITORY = 'GENRES_REPOSITORY';
