export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const USERS_REPOSITORY = 'USER_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const GENRES_REPOSITORY = 'GENRES_REPOSITORY';
export const CREDITS_REPOSITORY = 'CREDITS_REPOSITORY';
export const PERSONS_REPOSITORY = 'PERSONS_REPOSITORY';
export const MOVIES_REPOSITORY = 'MOVIES_REPOSITORY';
