export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PAYMENT_QUEUE_SERVICE = 'PAYMENT_QUEUE_SERVICE';
export const PAYMENT_EVENT_QUEUE = 'PAYMENT_EVENT_QUEUE';
export const PAYMENT_COMMAND_QUEUE = 'PAYMENT_COMMAND_QUEUE';
